#!/bin/bash

# Start Solr running as a background process on the local machine,
# possibly after downloading it to a nearby directory.

set -e

DEV=$(dirname "${BASH_SOURCE[0]}")
cd $DEV

USR_DIR=usr
EXAMPLE=$USR_DIR/solr-4.7.2/example

if [ ! -d $EXAMPLE ]
then
    mkdir -p $USR_DIR
    cd $USR_DIR
    curl -OL http://archive.apache.org/dist/lucene/solr/4.7.2/solr-4.7.2.tgz
    tar xzf solr-4.7.2.tgz
    cd ..
fi

echo 'Installing Solr XML schema'

./django build_solr_schema > $EXAMPLE/solr/collection1/conf/schema.xml

echo 'Running Solr in the background'

cd $EXAMPLE
rm -f nohup.out
log_file=output.log
nohup java -jar start.jar "$@" > $log_file 2>&1 &
echo "Check $PWD/$log_file for startup success/failure"
